[tool.black]
line-length = 79

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "W", "D1"]

[tool.ruff.lint.per-file-ignores]
"./tests/*" = ["E501"]

[tool.ruff.lint.pydocstyle]
convention = "google"